version: '3.4'

networks:
  backend:

services:
  moviedb:
    container_name: movie-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@12345#
      - MSSQL_PID=Evaluation
    networks:
      - backend
    ports:
      - 8001:1433   
  movieapi.api:
    container_name: movie-api
    image: ${DOCKER_REGISTRY-}movieapiapi
    build:
      context: .
      dockerfile: MovieAPI.API/Dockerfile
    networks:
      - backend
    ports:
      - 8002:8080
      - 8003:8081
    environment:
      - DB_HOST= moviedb
      - DB_NAME=MovieAPIDb
      - DB_SA_PASSWORD=password@12345#
    depends_on:
      - moviedb
